### ISSUE TITLE
Upgrade GCS plugin Google Cloud NIO dependency

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#100]
Now we use `0.30.0-alpha`, there is `0.40.0-alpha` already. Please see the [library page at GitHub](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-contrib/google-cloud-nio).

**Comment by dmytro-grankin** [comment]
Closing the issue since the GCS plugin and the dependency was removed in #122.
