### ISSUE TITLE
Migrate all repositories to travis-ci.com

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#105]
See [Travis blog post](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org) for the details.

**Comment by armiol** [comment]
@dpikhulya FYI. We need to migrate `SpineElements` as well.

**Comment by alexander-yevsyukov** [comment]
@armiol, are we done with this?

**Comment by armiol** [comment]
`SpineElements` are now migrated to `travis-ci.com`.
