### ISSUE TITLE
Consider migrating to API Guardian

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#112]
Now we use own annotations similar to one available in gRPC.
The advantage of migrating to [API Guardian](https://github.com/apiguardian-team/apiguardian) is simple: have the same set of annotations for all our code, which has the following implications:

  * Unified tooling. We can apply the same verification, testing, and documentation tools.
  * Unified learning: in each project people would use the same set of annotations.

I found this library via analyzing dependencies of NullAway. It's being [used by JUnit 5](https://junit.org/junit5/docs/5.1.0-RC1/release-notes/#release-notes-5.1.0-M2-overall-improvements).

**Comment by alexander-yevsyukov** [comment]
@armiol, have a look at this issue. We need to decide on this soon. We sill will be able to change it after v1.0 release, but there are other products that may benefit from this decision too.

**Comment by alexander-yevsyukov** [comment]
Recent [communications](https://issues.sonatype.org/browse/OSSRH-34409) from the people behind the project on deploying the artifact to Maven central.

Currently there's no site behind apiguardian.org. The comments for the issue confirm the ownership for the domain.

**Comment by armiol** [comment]
I think that `@SPI` annotation is difficult to emulate with [the number of options in API Guardian](https://github.com/apiguardian-team/apiguardian/blob/master/src/main/java/org/apiguardian/api/API.java#L76). 

```java
@SPI
public class AbstractEntity {...}
```
gives a proper intention, while
```
@API(status = Status.STABLE)
public class AbstractEntity {...}
```
has a different semantics.

**Comment by alexander-yevsyukov** [comment]
Agree. `@SPI` is a different thing, and may not be applicable to some of the projects. But the rest looks common.

**Comment by alexander-yevsyukov** [comment]
And we may contact these guys asking for an extension.

**Comment by armiol** [comment]
See https://github.com/apiguardian-team/apiguardian/issues/11.

**Comment by alexander-yevsyukov** [comment]
Assuming the API Guardian is not going to change, the migration looks impractical to us.
