### ISSUE TITLE
Generate VBuilders allowing ignoring return values of setters

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#117]
A likely usage of a `VBuilder` instance is this:

```java
 getBuilder()
     .setSomeValue(event.getSomeValue());
     .setAnotherValue(event.getAnotherValue());
```
or

```java
MyState newState = MyState
     .newBuilder()
     .setSomething(...)
     .setSomethingElse(...);
getBuilder().mergeFrom(newState);
```

ErrorProne would complain on ignoring return values of the last builder setter or of `mergeFrom()`.

It would be good to annotate the generated VBuilder methods with `@CanIgnoreReturnValue` to save users time on suppressing the warnings in each event applier.

**Comment by armiol** [comment]
Implemented.
