### ISSUE TITLE
Split `Options` into separate classes

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/base#127]
Currently, `Options` utility is a dump of all the custom option extractor methods. It should be, at least, split into separate classes. Another possible approach is to wrap the Protobuf descriptors and extract custom options with instance methods.

**Comment by alexander-yevsyukov** [comment]
@armiol, it would be good if @serhii-lekariev finish assignments from @dmdashenkov, _before_ getting new ones.
