### ISSUE TITLE
Allow narrower interfaces for generated messages

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#19]
When defining a domain model it may be necessary to group generated messages under a common interface derived from `Message`. 

For example, I want to group all commands for the `Task` aggregate under `TaskCommand` “umbrella”, so that I can restrict a type `C extends TaskCommand` instead of `C extends Message`.

It is suggested to introduce two options of the `string` type:
  * File option named `every_is` — makes all top level messages defined in a file to implement the interface derived from `Message`, which is named after the value of the option.
  * Message option named `is`, which does the same but only for one type.

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, assuming #43 is closed, can we consider this issue closed too?

**Comment by alexander-yevsyukov** [comment]
@armiol, if this is done, why don't we start using `CommandMessage` and `EventMessage` soon instead of postponing it to `v2`?

**Comment by alexander-yevsyukov** [comment]
@armiol, #20 mentions that the `base` package does not know about `Rejection`, which is true, but we can probably have a plug-in API for model compiler so that the `core-java` sub-project defines that things coming from `*events.proto`  are `EventMessage`s, `*commands.proto` are `CommandMessage`s, and `*rejections.proto` are `RejectionMessage`s

**Comment by dmdashenkov** [comment]
@alexander-yevsyukov, this issue is apparently not closed by mistake.
Closing now.
