### ISSUE TITLE
Build failing with missing `spine-protoc-plugin-0.10.89-SNAPSHOT.jar`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#195]
I've just attempted to re-build `base` on another computer, and it failed tests `ProtoAnnotatorPluginShould`, `RejectionGenPluginShould`, `ValidatingBuilderGenPluginShould`.

All the tests seem to fail because of the following error:

```
* What went wrong:
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: Error: Unable to access jarfile /private/var/folders/sj/f13l67ds5d9gz9mlsm7hnmrc0000gn/T/.gradle-test-kit-sanders/test-kit-daemon/4.10.1/.spine/spine-protoc-plugin-0.10.89-SNAPSHOT.jar
  --spineProtoc_out: protoc-gen-spineProtoc: Plugin failed with status code 1.
```

I've checked. There is no `.spine` sub-directory under `4.10.1`.

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, please look into this as I won't be able to continue my work in the branch `reduce-warnings`.

**Comment by dmdashenkov** [comment]
@alexander-yevsyukov, I've pushed a couple commits into `update-base`. One removes the JCenter and Maven Central repositories, which (for reasons unknown) cause the build to fail for me. The other one fixes the tests. 

This version works for me now. Please check.
