### ISSUE TITLE
Invalid `required` validation for number fields

### ISSUE THREAD

**Issue by mdrachuk** [SpineEventEngine/base#197]
Right now the required validation errors for number fields results in unclear `Value must be set.` error if the integer part of the number is `0`. This conflicts with cases when a `0` value is set. This behavior is not documented for the protobuf `required` option. 

Furthermore, only an integer part of double is considered when checking `double` and `float` values. Thus a required double field with `0.9` value will result in `Value must be set.` error.

Possibly, the `required` validation is semantically invalid for number fields. Can we consider using `min` and `max` validation instead of `required`, making `required` throw an error for `int32`, `int64`, `uint32`, `uint64`, `float` and `double` message fields?

**Comment by dmdashenkov** [comment]
The `0` for integers pars seems OK. [Here](https://developers.google.com/protocol-buffers/docs/proto3#default) is the spec describing the default values of the message fields. However, `min`-`max` validation does sound more reasonable.
