### ISSUE TITLE
Allow narrower generation for rejections

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#20]
Now our code generation of rejections creates classes implementing `ThrowableMessage`. The `core-java` project needs a narrower interface called `CommandRejection`. We cannot have this interface in this project because there's no notion of command at this level.

We need to be able to customize code generation so that it would be possible to use an interface derived from `ThrowableMessage`.

**Comment by armiol** [comment]
`RejectionMessage` marker interface is now being added to the generated rejections.
