### ISSUE TITLE
The `valid` option doesn't cause validation of a field with the default value

### ISSUE THREAD

**Issue by dmytro-grankin** [SpineEventEngine/base#241]
The `valid` option has effect only if a field is set to a non-default value (see `MessageFieldValidator.shouldValidateFields()`).

For example, we have two declarations:

```proto
message StringWrapper {
    string value = 1 [(required) = true];
}

message Message {
    StringWrapper string = 1 [(valid) = true];
}
```

Then, the following message is considered valid:

```java
Message message = Message.newBuilder()
    .setString(StringWrapper.getDefaultInstance())
    .build();
Validate.checkValid(message); // passes the check
```

In this case, I expect a validation error saying that `StringWrapper.value` should be set to a non-default value.

**Comment by dmdashenkov** [comment]
This is now the expected behaviour.
