### ISSUE TITLE
`findEnrichments` task is not executed after changes in Protobufs

### ISSUE THREAD

**Issue by dmytro-grankin** [SpineEventEngine/base#242]
Now, if a user changes declarations of Protobuf messages on which the enrichments depend on, and regenerated messages, the `findEnrichments` task is not executed.

So, to successfully regenerate Protobufs and enrichments I need to execute `gradlew generateProto findEnrichments` instead of just `gradlew generateProto`.

It happens because `findEnrichments` task is inserted after `compileJava` task. Instead, it would be better to insert the task after `generateProto`.

**Comment by alexander-yevsyukov** [comment]
Closing as outdated.
