### ISSUE TITLE
StringifierRegistry allows to conduct type mistakes

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/base#262]
It is now possible to register a `Stringifier` that is not even capable of working with a particular `Type` in the `StringifierRegistry`:
```java
public class OrderIdStringifier extends Stringifier<OrderId>{
    ...
}

StringifierRegistry.getInstance().register(new OrderIdStringifier(), String.class);
```

Maybe it worth enforcing the type for which we are registering a Stringifier? Use `Class<T>` instead of `Type` in the `register` method here:
```java
public <T> void register(Stringifier<T> stringifier, Type typeOfT) {
    checkNotNull(typeOfT);
    checkNotNull(stringifier);
    stringifiers.put(typeOfT, stringifier);
}
```

**Comment by alexander-yevsyukov** [comment]
The 2nd parameter of `register()` is `Type` to allow custom stringifiers for parameterized classes with different generic parameters.
