### ISSUE TITLE
Don't depend on published `spine-base` in test Gradle projects

### ISSUE THREAD

**Issue by dmytro-grankin** [SpineEventEngine/base#271]
Now, test Gradle projects (for `ProtoJsPlugin` and `ModelCompiler`) have the dependency as follows:

`implementation "io.spine:spine-base:$spineVersion"`

Such an approach is not perfect since it requires the `spine-base` artifact to be published locally each time before running tests.

The projects should be configured to use actual `base` instead of the latest published artifact.

**Comment by alexander-yevsyukov** [comment]
Closing as outdated.
