### ISSUE TITLE
Deprecation warning when compiling `base`

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/base#276]
When building the project, a warning pops up in the console:
```
<...>/base/base/generated/main/java/com/google/protobuf/compiler/PluginProtos.java:1206: warning: [deprecation] PARSER in FileDescriptorProto has been deprecated
                  input.readMessage(com.google.protobuf.DescriptorProtos.FileDescriptorProto.PARSER, extensionRegistry));
```

Note that the warning points to a generated class from the Protobuf standard library.

**Comment by alexander-yevsyukov** [comment]
We can add `@Generated` manually after protoc finishes. It should make Error Prone happy.
See related issues in:
 * Protobuf: https://github.com/protocolbuffers/protobuf/issues/2513

**Comment by alexander-yevsyukov** [comment]
No longer relevant.
