### ISSUE TITLE
Allow `Logging` interface to reset logging

### ISSUE THREAD

**Issue by serhii-lekariev** [SpineEventEngine/base#278]
Right now, `Logging` interface declares a `redirect(SubstituteLogger log, Queue<SubstituteLoggingEvent> queue)` method, which redirects logging of the `log` object to the specified queue.

It doesn't, however, declare a method to reset the logging back to the specified `log` object.

Right now, all test that call `redirect` do it for every test in the suite.

Example:

```java
@Test
void testWarnings() {
Logging.redirect((SubstituteLogger) Logging.get(ClassThatProducesWarnings.class),
                 new ArrayDeque<>());
}
```
After this test runs, no logging produced by `ClassThatProducesWarnings` is going to be seen for the rest of the test suite.

Being able to call something like`Logging.reset(ClassThatProducesWarnings.class);` would make sense.

**Comment by alexander-yevsyukov** [comment]
Can we make it in a non-static way? For example, `log().redirect(new ArrayDeque<>())`, and then 
`log().cancelRedirection()`.

**Comment by alexander-yevsyukov** [comment]
No longer relevant since we migrated to Flogger.
