### ISSUE TITLE
Add type information to warnings

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/base#290]
When a validation option misuse warning is logged, the name of the misusing type should be added to the message. Currently, it's just the type of the field itself.

**Comment by alexander-yevsyukov** [comment]
@serhii-lekariev, I presume it should be fixed by one of the recent PRs. Please check.

**Comment by serhii-lekariev** [comment]
Fixed as a part of https://github.com/SpineEventEngine/core-java/pull/930.

**Comment by serhii-lekariev** [comment]
Fixed by https://github.com/SpineEventEngine/base/commit/a0a29c7fea5f1b494fe2cd9a6fb2a6d1f8a9d240 in [this PR](https://github.com/SpineEventEngine/base/pull/311).
