### ISSUE TITLE
Enhance code generation for enrichments

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#297]
Now Model Compiler gathers information about enrichments into the property file (named `enrichments.properties`) which maps a type of an enrichment to the type it enriches.

Obtaining an enrichment from `EventContext` is currently awkward. Users of the framework need a more straight (and domain-driven!) API for obtaining enrichment message. It is suggested to extend Model Compiler so that generated enrichment messages provide easier API.

Suppose we have an enrichment message, which is declared like this:
```proto
// Enrichment for the `OrderUpdated` event which provides sections of the updated order.
message SectionList {
     option (enrichment_for) = "ackme.ordering.OrderUpdated";
     repeated SectionId section = 1;
}
```
We want to have event handler of the enriched event to look like this:
```java
@Suscribe 
void to(OrderUpdated event, Context ctx) {
   SectionList sections = SectionList.fromOrderUpdated(ctx);
   // ...
}
```
Here the call `SectionList.fromOrderUpdated() ` is a generated static factory method.
Presumably, each enrichment message would implement an interface `EnrichmentMessage`.

When working on this issue please pay attention to providing customization of the type of the interface used by the Model Compiler (via `generateInterfaces` Gradle script closure).

**Comment by alexander-yevsyukov** [comment]
@armiol, @dmdashenkov, @yuri-sergiichuk, this issue summarizes our discussion. Please see if you want to add or change something.

**Comment by yuri-sergiichuk** [comment]
As discussed vocally, the `EnrichmentMessage` interface should not be parameterized, cause it'll not work as soon as we'll have at least two enrichment targets:
```protobuf
// Enrichment for the `OrderUpdated` and `OrderCreated` events which provides sections of the updated order.
message SectionList {
     option (enrichment_for) = "ackme.ordering.OrderUpdated,"
                               "ackme.ordering.OrderCreated";
     repeated SectionId section = 1;
}
```

**Comment by alexander-yevsyukov** [comment]
@yuri-sergiichuk, isn't it already resolved?

**Comment by yuri-sergiichuk** [comment]
Yeah, it is obsolete.
