### ISSUE TITLE
Drop support of nested enrichments and FQN (by) option

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/base#310]
It should be not possible to define enrichments as nested event messages, as such usage of enrichments is misleading and does not stand for the actual enrichment purpose.

Also, in order to make the current enrichments syntax more strait-forward and precise enrichments should not be automatically discovered with FQN in `(by)` option.

**Comment by alexander-yevsyukov** [comment]
No longer applicable since enrichments no longer use proto options.
