### ISSUE TITLE
External validation constraint must be defined within a numeric type

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#319]
We should not allow min/max value of an `int32` field defined as `"3.14"`. Such a definition is a programming error, and should be reported as such on compile-time.

**Comment by alexander-yevsyukov** [comment]
@serhii-lekariev, fixed?

**Comment by armiol** [comment]
@dmdashenkov please have a look. I am not sure we support "compile-time" checks for the external validation constraints.

**Comment by dmdashenkov** [comment]
This is handled in all the cases except two:
 - validation code generation is disabled;
 - external constraints.
