### ISSUE TITLE
Generated interfaces for event messages or command messages should extend corresponding interfaces

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#348]
When I write something like in an `events.proto` file:
```proto
message OrderCreated {
    option (is) = { java_type: "OrderEvent", generate: true };
    string order_id = 1;
}
```
I expect that the generated interface `OrderEvent` implements `EventMessage` since we are in the `events.proto` file and all those types are `EventMessage`s by convention.

Instead, the generated code simply extends `Message`.

**Comment by dmdashenkov** [comment]
This might be the desired behaviour.

In the example, `OrderCreated` implements both `OrderEvent` and `EventMessage`.
If a user wants `OrderEvent` to extend `EventMessage`, they should create the interface manually.

**Comment by dmdashenkov** [comment]
As discussed, leaving current behaviour as is.
