### ISSUE TITLE
Custom source sets are not supported

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/base#358]
It is currently impossible to define a custom source set in Gradle for a project with model compiler.

```gradle
sourceSets {
    functionalTest { /* ... */ }
}
```

This configuration breaks the build at configure time as `writeDescriptorReference` task is added twice: to the `main` source set and to the `functionalTest` source set.

We should generate names for custom tasks basing on the source set name at runtime instead of hardcoding them.

**Comment by alexander-yevsyukov** [comment]
Addressed by [this PR from mc-java](https://github.com/SpineEventEngine/mc-java/pull/18).
