### ISSUE TITLE
Spine Protoc plugin should allow similar selectors with different targets

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/base#367]
In order to provide the ability to apply multiple interfaces or method factories to the same selector, we should change our current Spine Protoc plugin Protobuf configuration and make `uuidConfig` `repeated`.

Within the Gradle DSL configuration, we now should distinguish selectors by patterns **and** interfaces. In such a way users would be able to configure multiple interfaces or method factories for the same selector.

As a part of this change, the `ignore` semantic should be changed: users should supply both `target` and `selector` to actually ignore smth, e.g. to ignore the default interfaces generation for Events we should use the following configuration:
```gradle
modelCompiler {
     generateInterfaces {
          ignore filePattern().endsWith("events.proto"), "io.spine.base.EventMessage"
     }
}
```

**Comment by alexander-yevsyukov** [comment]
@yuri-sergiichuk, is it still relevant?

**Comment by yuri-sergiichuk** [comment]
Looks like it's not relevant anymore.
