### ISSUE TITLE
VBuilders miss `getCase` methods

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/base#377]
Consider the following example Protobuf message:
```protobuf
message MessageWithOneOf {

    oneof value {
        string string_value = 1;

        int32 int_value = 2;

        bool bool_value = 3;
    }
}
```

The `MessageWithOneOf.Builder` has a `getValueCase` method, but the `MessageWithOneOfVBuilder` does not.

**Comment by dmdashenkov** [comment]
Maybe, we should make validating builders implement `...OrBuilder` interfaces. This way we're guaranteed to stay compliant with the Protobuf API.
