### ISSUE TITLE
Generate `base` Protobuf messages with default model compiler configuration

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/base#389]
Currently, proto messages defined in the `base` module have `VBuilder`s, but they lack helper methods like `vBuilder` and `toVBuilder` because Spine protoc plugin is not applied when the protos are generated.

Technically, it should be possible to tune up (or refactor) our `base-validating-builders` module to re-generate `base` protos with Spine protoc plugin.

**Comment by alexander-yevsyukov** [comment]
@yuri-sergiichuk, is it still relevant?

**Comment by yuri-sergiichuk** [comment]
Not relevant anymore. We have `vBuild` method now in the base protos.
