### ISSUE TITLE
Extend Validating Builders with ability to modify repeated fields

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#402]
In order to replace a repeated field of a Validating Builder, we need to have a code like this:

```java 
static <T extends Message, P> 
boolean replace(List<T> items, T item, Function<T, P> prop) {
    for (int i = 0; i < items.size(); i++) {
        T current = items.get(i);
        P passed = prop.apply(item);
        P found = prop.apply(current);
        if (passed.equals(found)) {
            items.set(i, item);
            return true;
        }
    }
    return false;
}
```
The calling code would look like:

```java
@Subscribe
void updated(Column column) {
    boolean replaced = replace(builder().getColumn(), column, Column::getId);
    if (!replaced) {
        builder().addColumn(column);
    }
}
```

It would be more convenient to write:
```java
boolean replaced = builder().replaceColumn(column, Column::getId);
if(!replaced) {
    builder().addColumn(column);
}
```
It would require generating `replaceXxx()` methods for all repeated fields.

Also, `removeXxx()` accepting a predicate is needed.

**Comment by armiol** [comment]
@alexander-yevsyukov @dmdashenkov 
Regarding the removal. There is  [`Iterables.removeIf(iterable, predicate)`](https://google.github.io/guava/releases/27.0-jre/api/docs/com/google/common/collect/Iterables.html#removeIf-java.lang.Iterable-com.google.common.base.Predicate-).

**Comment by armiol** [comment]
So basically, we can rewrite the code you wanted as:
```java
// Remove the column if it exists.
Iterables.removeIf(builder().getColumns(), 
                   c -> {c.getId().equals(column.getId())});
// Add the column, effectively replacing it if it was removed previosly.
builder().getColumns().add(column);
```

**Comment by alexander-yevsyukov** [comment]
Yes, but this changes the order.

**Comment by armiol** [comment]
OK, there is one more option [using JDK API](https://stackoverflow.com/a/35821940).

**Comment by alexander-yevsyukov** [comment]
Since we now use standard builders, this issue is no longer applicable.
