### ISSUE TITLE
`base` Protobuf Builders do not compile under Java 8

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/base#431]
When compiling code Java 8 `javac` and using `base` as a library, message builders declared in `base` are not recognized to implement `ValidatingBuilder`. This leads to compilation errors when trying to call `vBuild()` or cast a builder instance to `ValidatingBuilder`.

When using Java 9 `javac`, this issue is not reproducible.
Since ErrorProne substitutes `javac` of version 8 for version `9`, this issue is not reproducible when using ErrorProne.

Also, when de-archiving the `base` artifact and adding it to compile classpath as a folder, the issue is not repreducible as well.

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, please see if it's still relevant. We may postpone it to v2, if needed.

**Comment by dmdashenkov** [comment]
It seems that this issue is no longer reproducible. With or without the ErrorProne plugin, the build passes.
