### ISSUE TITLE
Add message casters for Protobuf descriptors

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/base#437]
The `(distinct)` option applied on enum values fails to actually convert an enum value to `Any` because of the constraint iterates over `EnumValueDescriptor` instead of actual enum values.

In order to support consistent behavior across all possible types, we should consider adding appropriate message casters for such a situation.

**Comment by alexander-yevsyukov** [comment]
@yuri-sergiichuk, so we cannot put `(distinct)` for a repeated enum field right? If so, it's a bug.
