### ISSUE TITLE
Support JDK 11+ when building Spine

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/base#457]
Currently, the codebase relies on JDK 8 implementation at the build time. We have `1.8` as a target to cover as many platforms as possible, including Google AppEngine Standard. 

Those wishing to use Spine artifacts with JDK 9+ may use the pre-built binaries available in the 
Spine Maven repository.

Post-1.0 release we should support at least JDK 11 at build-time.

**Comment by alexander-yevsyukov** [comment]
Done already.
