### ISSUE TITLE
Enable `ModelVerifier` to check if a message-handling method is formed correctly

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/base#49]
For example, it should break the compilation when facing the following construct:
```java
@Assign
private void handle() {
    // This command handler is invalid, as it violates several rules. 
}
```

**Comment by alexander-yevsyukov** [comment]
@serhii-lekariev, if it's not yet done, please talk to @dmdashenkov on priorities.

**Comment by serhii-lekariev** [comment]
Fixed by https://github.com/SpineEventEngine/core-java/pull/930.
