### ISSUE TITLE
`.proto` file with no messages fails to pass through `ProtoAnnotatorPlugin`

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/base#509]
Protobuf compiler seems to support and handle the `.proto` files like this one:
```proto

syntax = "proto3";

package spine.test.delivery;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.test.delivery";
option java_outer_classname = "DeliveryCalcProto";
option java_multiple_files = true;

```
(notice, no messages declared!)

The Java class is generated normally, along with the file descriptor and options.

However, the `ProtoAnnotatorPlugin` fails with the `IllegalStateException`:

```java
 // FileSet.java:137 in `base`, version 1.4.1.
 throw newIllegalStateException("Some files are not known.");
```

We should support such a use case as well.

**Comment by dmdashenkov** [comment]
Resolved in #515.
