### ISSUE TITLE
Allow requiring `oneof` values

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#521]
In some cases, it is needed to require that one of the fields coming under `oneof` is set. For example, if we create a user account it can be either `person` or `service` field must be set. In order to arrange such a requirement, we can use the following construct:

```protobuf
option (required_field) = "person|service";

// ...

oneof type {
    // The user is a human.
    PersonProfile person = 2;

    // The user is a computer program.
    ServiceProfile service = 3;
}

```
The problem with this approach is that it's fragile and breaks when we:
  1. rename fields;
  2. add fields under `oneof`.

We cannot annotate `oneof` itself, but we cannot reduce the dependency on the content of it by telling the compiler: “We do want one of the things coming under that `oneof`.” Here's how:

```protobuf
// One of the fields coming under `type` `oneof` must be populated.
option (required).field = "type";
```
This is still fragile for renaming the `oneof` itself, but they tend to be more stable, and it's still safer as we refer only one element.

**Comment by dmdashenkov** [comment]
We _can_ mark `oneof`s with custom options. I suggest we add a `(required_fields)` option for `oneof`s and allow using `oneof` names in the `(required_field)` option.

**Comment by armiol** [comment]
@dmdashenkov I would have both. 

But... Can we have a `(required)` option for `oneof`, not the `required_fields`? Or maybe I don't understand how it's going to look from your perspective. Could you post a sample?

**Comment by dmdashenkov** [comment]
@armiol, we need a distinct name because in Java all the extension options are represented as static fields in a single class.

Example:
```proto
message User {
    // ...
    oneof type {
        option (required_fields) = true;

        PersonProfile person = 2;

        ServiceProfile service = 3;
    }
}
```

**Comment by alexander-yevsyukov** [comment]
The problem with plural here is that it sounds as if _all of them_ are required, which is not the case. It's a bit misleading.

**Comment by alexander-yevsyukov** [comment]
How about `is_required`:

```proto
message User {
    // ...
    oneof type {
        option (is_required) = true;

        PersonProfile person = 2;

        ServiceProfile service = 3;
    }
}
```
