### ISSUE TITLE
Ensure every Spine library update increments the library version

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/base#537]
At the moment some of the pull requests to Spine libraries may choose not to update the library version — as the changes may be insignificant in terms of the code modification (e.g. correcting typos).

However, in some cases the committer may forget to increase the version of the library and commit the breaking changes. In this case the published library overwrites the previous version in the artifact repository and potentially breaks all the dependant libraries as well.

To prevent this, each PR must increase the library version. In order to check that, an automated check should be performed in the scope of the build. 

As long as it's impossible to check the version increment locally, it is proposed to run this check in the scope of CI build on every commit to the PR. This will encourage the PR author to increase the version right away.

In order to achieve that, the automated script should fetch the library version from the latest `master` codebase and compare it with the version in the PR-underlying branch.

Special attention should be paid to the `web` library, which supplies two distinct versions: one for the Java codebase and another one for the JS artifacts.

The target repository for this feature is `config`. The language is Kotlin.

**Comment by dmdashenkov** [comment]
Now we have the `IncrementGuard` plugin, which adds a task which performs the described check. Note that the task checks all the available versions in the Maven repository, not only the version in `master`.

To enable the check, add the following to the Kotlin Gradle script:
```kts
apply<IncrementGuard>()
```
