### ISSUE TITLE
Synchronize Gradle wrappers among builds

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/base#538]
Now that we have custom pull scripts (see #534), we can sync the Gradle wrapper configs and JARs automatically upon pull instead of manually updating `./gradle/wrapper`, `./tools/smoke-tests/gradle/wrapper`, and `./base-validating-builders/gradle/wrapper`.

**Comment by alexander-yevsyukov** [comment]
This issue relates to #578.

**Comment by alexander-yevsyukov** [comment]
No longer relevant to this repo and is addressed in `mc-java`.
