### ISSUE TITLE
`generateColumnInterfaces` doesn't work, sporadically

### ISSUE THREAD

**Issue by serhii-lekariev** [SpineEventEngine/base#548]
`generateColumnInterfaces` is a task that generates `MessageWithColumns` interfaces for `Message`s that declare fields that are columns.

#### Bug description

Sometimes the task doesn't get executed and no interfaces are generated. Whenever this happens, `Fields` inner class is still generated, so, presumably, only the part relevant to the column interfaces is broken. No errors are ever logged. When running with `--info`, Gradle says that the task is `UP-TO-DATE`.

#### Reproduction

The bug was initially spotted in the integration tests in the `web` repository.

I've not found a way to reproduce it consistently. Sometimes, running `clean build` reproduces it. Sometimes, `build`ing, then manually deleting `generated` and `build`, then `build`ing again fixes it and the interfaces are generated again. This doesn't seem to happen on CI ever.

**Comment by yuri-sergiichuk** [comment]
I'm seeing the same issue with `generateRejections` from time to time. Running Gradle with `--rerun-tasks` helps.

**Comment by alexander-yevsyukov** [comment]
No longer relevant.
