### ISSUE TITLE
Move environment types into sub-package

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#595]
`Environment` and related types are now under the `io.spine.base` package. It would be better to move them under `io.spine.environment` so that this small sub-system is easier to understand.

**Comment by alexander-yevsyukov** [comment]
To be mentioned as breaking change in [Release Notes](https://github.com/SpineEventEngine/SpineEventEngine.github.io/issues/409).

**Comment by armiol** [comment]
This is also done for `1.9.0` (mentioned as breaking change). So it will NOT be a breaking change in 2.0.
