### ISSUE TITLE
Investigate on `FloggerSplitLogStatement` in `Logging`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#612]
The `Logging` interface causes `FloggerSplitLogStatement` [error](http://errorprone.info/bugpattern/FloggerSplitLogStatement) in ErrorProne because of underscored methods that return `Flogger.Api` instances. The error synopsis does not tell much about why it breaks logging. We need to investigate on this. For now the error is suppressed.

**Comment by dmdashenkov** [comment]
The breaking refers to the fact that the `Flogger.Api` memoizes its creation site (line number, method name, etc.) and prints it to the log instead of the actual site where the `log()` method is called.

As of now, we're suppressing this error in `config/gradle/javac-args.gradle`.

**Comment by alexander-yevsyukov** [comment]
Outdated.
