### ISSUE TITLE
Change `duplicateStrategy` to `WARN` and fix duplicating Gradle task output

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#657]
Migration to Gradle 7.1.1 required configuring `duplicatesStrategy` specifically because we have duplicating output files in some of the tasks.

Currently the strategy is set to `DuplicatesStrategy.INCLUDE` because the `WARN` level produces too much console output.

We need to set it back to `WARN`,  investigate on duplicates and try to avoid them, after all depending projects finish migration to Gradle 7.

**Comment by dmdashenkov** [comment]
We add directories to `sourceSet`s multiple times. Or, to be more precise, Gradle adds them automatically (sometimes, it's a 3d party plugin that does it, e.g. Protobuf Gradle plugin), and then we add them manually.
If we avoid adding directories to `sourceSets`, the error goes away.

After I'm done moving Model Compiler components around, I could apply this fix to our repos, if none beats me to it.

**Comment by alexander-yevsyukov** [comment]
Addressed already.
