### ISSUE TITLE
Make options `is` and `every_is` multi-platform

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#66]
The documentation of the `is` option now says:

```proto
// Specifies the name of a Java interface to be implemented by this message.
...
```

Although this is true in the current implementation, this is not exactly what we want to do when defining a type. We way to say that a type annotated in this way is a specific kind of message _and_ for Java this fact would be reflected in generated code in Java-specific way.

When we have code generation implemented for another programming language, the option description would be extended for that programming language.

The Model Compiler should have an API that would allow to match values from the `is` options to a value specific for the programming language. For Java it would a fully-qualified interface name.

**Comment by dmdashenkov** [comment]
@alexander-yevsyukov, not sure if this issue is only connected to the doc part.

In fact, the implementation is Java-oriented as well, since the value of the option represents a __Java__ type FQN (and, in some cases, a non-qualified type name).

Maybe, this problem is a bit deeper (e.g. with the option name).

**Comment by alexander-yevsyukov** [comment]
As discussed verbally, we should use options `is` and `every_is` to mark messages on the level of the model. It would be just a marker string (not a FQN of any kind). Then, code generator for a particular language would transform those marker strings into a language-dependent implementation. For Java it would be an FQN interface name.
