### ISSUE TITLE
Describe version 1.7.4

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#676]
The [latest stable release under v1.*](https://github.com/SpineEventEngine/base/releases/tag/latest-v1) is not documented. It would be good to tell what's in there and make it more visible for the visitors.

**Comment by yuri-sergiichuk** [comment]
The new v1.7.4 [release](https://github.com/SpineEventEngine/base/releases/tag/v1.7.4) is created in GitHub.

I've also created a new v1.7.3 [release](https://github.com/SpineEventEngine/web/releases/tag/v1.7.3) for the [`web`](https://github.com/SpineEventEngine/web) repository.

For the other repos, it looks like only copyright notice was changed for the stable version of Spine, so there is no relevance in creating separate release notes.
