### ISSUE TITLE
Allow excluding types from `VBuilder` generation

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#71]
Most of the `VBuilder` types that are now put under the folder `generated/spine/` are not going to be used.

The Compiler should allow excluding certain types from generation. Or, better, generate `VBuilder`s only for types that represent entity states.

We have `EntityOption`, which allows to mark a message as an entity state:

```proto
     message MyAggregate {
          option (entity).kind = AGGREGATE;
          ...
     }
```

If the `kind` option is missing in a message, we should not generate `VBuilder`.

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, do you see any problems with the approach suggested above?

@armiol, FYI.

**Comment by dmdashenkov** [comment]
I would not restrict builders to entity types only. They are at least helpful when constructing domain objects, DTOs, etc.

Instead, we can disable `VBuilder` generation for types that do not include (directly or recursively) any validation options and, of course, keep all entity types as well).

For example, if a type declares a `required` field, the building is generated.

The external validation rules (see `(validation_for)`) should be checked as well.

All the other Protobuf types may not require a validating builder.

**Comment by alexander-yevsyukov** [comment]
For “DTO”s we have `Projections`. 

I do agree that `VBuilder` for a value object with one or more validating attributes would be a useful thing.

**Comment by dmdashenkov** [comment]
Now irrelevant, as all the generated code resides in the message class itself.
