### ISSUE TITLE
API issues in `AbstractValidatingBuilder`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#73]
### Over-exposed API
This abstract base has public methods that are not exposed by the interface `ValidatingBuilder`. These methods are called by derived classes. But are they intended to be called from somewhere else?

`protected` and presumably `final` should be quite enough for those methods.

### `ConversionException` is declared but not thrown
In:
 - `convertToMap()`
 - `convertToList()`

Assuming that `convert()` method does thrown an exception, having similar behavior for collections 
is a good idea. But if these methods (that are `public` now) would be hidden from the public API, it wouldn't make much sense.

**Comment by dmytro-grankin** [comment]
Closing the issue as it was fixed by https://github.com/SpineEventEngine/base/commit/94727cd090d39f766aa177bd26515d0e9a2cbce3 and https://github.com/SpineEventEngine/base/commit/e65396b150b3b5e79a69f776642e0b27a77c14c0.

**Comment by dmytro-grankin** [comment]
Closing the issue as it was fixed by https://github.com/SpineEventEngine/base/commit/94727cd090d39f766aa177bd26515d0e9a2cbce3 and https://github.com/SpineEventEngine/base/commit/e65396b150b3b5e79a69f776642e0b27a77c14c0.

**Comment by dmytro-grankin** [comment]
Closing the issue as it was fixed by https://github.com/SpineEventEngine/base/commit/94727cd090d39f766aa177bd26515d0e9a2cbce3 and https://github.com/SpineEventEngine/base/commit/e65396b150b3b5e79a69f776642e0b27a77c14c0.
