### ISSUE TITLE
Simplify `Stringifier.toString` call in Java

### ISSUE THREAD

**Issue by dmytro-kashcheiev** [SpineEventEngine/base#799]
Currently, when you write some complicated log message with several `Message`s, you should always call `Stringifier.toString(...)`. You can't statically import this `toString` method. As a result, the code doesn't look well. 

Currently, logging API calls look like this: 
```
_info().log("Importing `%s` user from `%s` domain.",
             Stringifiers.toString(userId), Stringifiers.toString(domain));
```

### Possible solutions:

1. Rename the method to `stringify(...)` so it's possible to import it statically;
```
_info().log("Importing `%s` user from `%s` domain.",
             stringify(userId), stringify(domain));
```

2. Add custom `io.spine.logging.LoggingApi` with the following method: `void log(String msg, Message... params)`
```
_info().log("Importing `%s` user from `%s` domain.", user, domain);
```

**Comment by alexander-yevsyukov** [comment]
> * Add some Spine-specific logging facade that accepts `Message` and automatically applies `Stringifier.toString(...)`.

@dmytro-kashcheiev, the first part is clear. I'm not quite sure about the second one. Please explain in more details. Give us  code snippets on what currently looks not so good, and how you'd like it to see.

**Comment by dmytro-kashcheiev** [comment]
@alexander-yevsyukov I've added more details to issue explanations with examples.
