### ISSUE TITLE
Repackage `io.spine.gradle.*` to `io.spine.tools.gradle.*`

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/base#82]
Currently `model-compiler` and `plugin-base` use `io.spine.gradle` as a base package. However, Gradle is just one of the alternative solutions, that we currently use. In future we add support for Bazel and Maven and the essence of the plugins will remain.

In order to emphasize that Gradle is just one of potential options (even if that's the only option for Spine users at the moment) we need to repackage the codebase to `io.spine.tools.gradle`.

**Comment by alexander-yevsyukov** [comment]
Already solved by on of the recent PRs.
