### ISSUE TITLE
Validate repeated fields with distinct entries

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/base#85]
For `repeated` fields, it is a common use case to contain only distinct entries, like in a Java `Set`. Sometimes, the uniqueness of a list entries is an important detail of a domain model.

We may introduce a field option to enforce a `repeated` field to contain distinct entries.
For example:
```proto
message Snowfall {

    repeated Snowflake snowflake = 1 [(distinct) = true];

    // ...
}
```

**Comment by alexander-yevsyukov** [comment]
@serhii-lekariev, implemented?

**Comment by serhii-lekariev** [comment]
It is, as a part of https://github.com/SpineEventEngine/base/pull/291.
