### ISSUE TITLE
Required enum fields should not say that "Value must be set"

### ISSUE THREAD

**Issue by mdrachuk** [SpineEventEngine/base#97]
This is a miss because Protobuf enum is required to have a default zero value, but this value may not signal that the field is empty. 

Instead, `FieldValidator` error message should specify that the enum fields marked as `required` cannot contain a default value. As a hint, it may also clarify that `UNKNOWN` value or it‘s alternative is required as a `0` default.

As of now `EnumFieldValidator` treats all values `<= 0` as missing values. 

A simple example is an event for a created task which contains some state:
```proto
message TaskCreated {

    TaskId task_id = 1;

    enum Status {
        TODO = 0;
        IN_PROGRESS = 1;
        DONE = 2;
    }

    Status status = 2 [(required)=true];
}
```

This event would not pass validation with a `TODO` status. The `FieldValidator` would state that the `status` field is failing the `required` constraint:
```
ValidationException{constraintViolations={"msgFormat":"Value must be set.","fieldPath":{"fieldName":["status"]}}}
```

The error message here is unclear and unspecific. Instead a violation should state that:
>Required enum field cannot be set to the zero value.

Same applies to all number types, where zero value must violate the `required` constraint with the following message:
>Required number field cannot be set to zero.

**Comment by alexander-yevsyukov** [comment]
Let's say that if something is zero, and we set that a field is `required`, we expect non-zero value.

For example, if we say...

```proto
message Item {
     uint32 price = 5 [(required)=true];
}
```
we assume that the price cannot be zero. Similarly to enums, we assume that “non-zero” value is required. Yes, it won't give us ability to have `TODO` as the default value in this case, but it's a minor loss as compared with ability to have validation in return for forcing having a zero-based enum item for undefined value.

**Comment by dmdashenkov** [comment]
@alexander-yevsyukov, could we discuss this issue in person?
`(required)` option does not work for number fields. Maybe, we should re-consider the behaviour for the enums as well?

**Comment by dmdashenkov** [comment]
As discussed with @armiol, enums should have the `UNDEFINED` value at `0` index, since it is the default value of the enum.

Though, the error message does require some improvements.

**Comment by dmdashenkov** [comment]
Now that the validation error always contains the validated message type and the invalid field, I consider this issue resolved.
